Fix build on older Linux where PTRACE_GETREGSET is missing
In file included from ../../gdbserver/../gdb/nat/x86-linux-tdesc.c:29:
../../gdbserver/../gdb/nat/x86-linux-tdesc.c: In function 'const target_desc* x86_linux_tdesc_for_tid(int, uint64_t*, x86_xsave_layout*)':
../../gdbserver/../gdb/nat/x86-linux-tdesc.c:90:19: error: 'PTRACE_GETREGSET' was not declared in this scope; did you mean 'PTRACE_GETREGS'?
   90 |       if (ptrace (PTRACE_GETREGSET, tid,
      |                   ^~~~~~~~~~~~~~~~
../../gdbserver/../gdb/nat/gdb_ptrace.h:142:30: note: in definition of macro 'ptrace'
  142 |   ptrace ((PTRACE_TYPE_ARG1) request, pid, addr, data)
      |                              ^~~~~~~